#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../../../lib", __dir__)
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "rbnotes"

DEBUG = true

module Rbnotes
  class App
    include CLI

    def initialize(conf_file = nil)
      unless conf_file
        @conf = default_conf
      else
        # ... load configuration file
      end
    end

    def default_conf
      {
        :repository_type => :file_system,
        :repository_name => DEBUG ? "sandbox/notes_dev" : "notes",
        :repository_base => File.expand_path("~"),
      }
    end

    def run(args)
      opts = get_global_opts(args)
      cmd = get_cmd_name(args, opts)

      Rbnotes::Commands.load(cmd, @conf[:plugins]).execute(args, @conf)
    end
  end
end

app = Rbnotes::App.new(nil)
app.run(ARGV)
